// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juodhpqkgpwkvddlxenz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1b2RocHFrZ3B3a3ZkZGx4ZW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDQzNTAsImV4cCI6MjA2NjAyMDM1MH0.1Enrm2D0ux0P-C1BzMrAEJktVIHRshiYDRo9xi2ETko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);